pipeline:
  ecr:
    image: plugins/ecr
    registry: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    region: ap-northeast-1
    tag: ${DRONE_TAG}
    file: Dockerfile 
    build_args: "GIT_TAG=${DRONE_TAG}"
    when:
      event: tag
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    deployment: httptestv4
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    container: httptestv4
    tag:
      - ${DRONE_TAG}
    when:
      state: success
  
  #test:

      #auth:
      #  image: plugins/ecr
      #  commands:
      #    - aws ecr get-login --region ap-northeast-1 | bash 
      #    - docker pull 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker:${DRONE_TAG}
      #  when:
      #    state: success

