pipeline:
  ecr-publish:
    image: plugins/ecr
    registry: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    region: ap-northeast-1
    tag: ${DRONE_TAG}
    file: Dockerfile 
    build_args: "GIT_TAG=${DRONE_TAG}"
    when:
      event: tag
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: 127.0.0.1:8080
    deployment: httptest
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    container: httptest
    tag: ${DRONE_TAG}
    when:
      state: success
  
  #test:
      #auth:
      #  image: plugins/ecr
      #  commands:
      #    - aws ecr get-login --region ap-northeast-1 | bash 
      #    - docker pull 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker:${DRONE_TAG}
      #  when:
      #    state: success

