#pipeline:
#  ecr:
#    image: plugins/ecr
#    registry: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com
#    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
#    region: ap-northeast-1
#    tag: ${DRONE_TAG}
#    file: Dockerfile 
#    when:
#      event: tag
#  test:
pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build
      - go test

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=myapp
