pipeline:
  ecr:
    image: plugins/ecr
    registry: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    region: ap-northeast-1
    tag: v20180703-v2
    file: Dockerfile 
