pipeline:
  ecr:
    image: plugins/ecr
    registry: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    region: ap-northeast-1
    tag: ${DRONE_TAG}
    file: Dockerfile 
    when:
      event: tag

  ecr:
    image: plugins/ecr
    registry: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com
    repo: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker
    region: ap-northeast-1
    tag: ${DRONE_TAG}
    pull: true
    when:
      state: success

  run:
    image: plugins/ecr
    detach: true
    commands:
      - docker run -p 80:80 hello
    when:
      status: success

      #check_running: 
      #  image: 862793644923.dkr.ecr.ap-northeast-1.amazonaws.com/test_k8sdocker:${DRONE_TAG}
      #  commands:
      #    - sleep 5
      #    - docker ps
      #  when:
      #    status: success

  test:
    image: golang
    commands: 
      - curl -v http://docker:80
    when:
      status: success
